### ISSUE TITLE
Update for IntelliJ IDEA 2020.3.1

### ISSUE THREAD

**Issue by nvx** [BudgieWatts/CertificatePlugin#3]
The plugin manager is reporting Incompatible: Requires IDE build 202.* or older when running IntelliJ IDEA 2020.3.1 (Looks to be 203.*)

**Comment by BudgieWatts** [comment]
Thanks for letting me know.  I've uploaded an update.  It says it can take up to two days for moderation but in my experience JetBrains are usually much quicker.

**Comment by nvx** [comment]
Looks like it's live already and working fine, cheers!
